import type { ReactNode } from 'react';

export type PrivacyArticle = {
  id: string;
  navLabel: string;
  cardTitle: string;
  content: ReactNode;
};

const p = 'text-[15px] leading-relaxed text-gray-600';
const ul = 'mt-2 list-disc space-y-2 pl-5 text-[15px] leading-relaxed text-gray-600';
const h3 = 'mt-6 text-base font-bold text-primary-black';

export const PRIVACY_ARTICLES: PrivacyArticle[] = [
  {
    id: 'article-1',
    navLabel: 'Article 1 — Introduction',
    cardTitle: 'Article 1 — Introduction',
    content: (
      <>
        <p className={p}>
          At Zena Technologies Limited (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), we take the privacy of every user of the Zena platform seriously. This Privacy Policy explains what personal data we collect, why we collect it, how we use it, with whom we share it, and the choices and rights available to you. It applies to our mobile application, website (www.zenaex.com), and all related services (collectively, the &quot;Platform&quot;).
        </p>
        <p className={`${p} mt-4`}>
          We operate in full compliance with applicable Nigerian data protection law, specifically the Nigeria Data Protection Act (NDPA) 2023, as enforced by the Nigeria Data Protection Commission (NDPC). Our practices also reflect obligations under the Central Bank of Nigeria (CBN) AML/CFT Framework and the Financial Action Task Force (FATF) standards for virtual asset service providers.
        </p>
        <p className={`${p} mt-4`}>
          By accessing or using the Platform, you acknowledge that you have read and understood this Privacy Policy and consent to our collection and processing of your personal data as described herein.
        </p>
        <p className={`${p} mt-4`}>
          <strong className="font-bold text-primary-black">IMPORTANT:</strong> We will never ask you to verify your identity or share personal information through social media direct messages, WhatsApp, or any channel outside the official Zena application and website.
        </p>
      </>
    ),
  },
  {
    id: 'article-2',
    navLabel: 'Article 2 — Who We Are and What Zena Is Not',
    cardTitle: 'Article 2 — Who We Are and What Zena Is Not',
    content: (
      <>
        <p className={p}>
          Zena is a borderless utility platform built for Africans. We provide multi-currency crypto wallets, crypto send/receive/swap operations, fiat conversion and payouts, utility bill payments, gift card trading, eSIM services, and agent-assisted OTC trading (E-Trade).
        </p>
        <p className={`${p} mt-4`}>To avoid any misunderstanding about the nature of our service, please note the following:</p>
        <ul className={ul}>
          <li>Zena is NOT a bank or licensed deposit-taking institution.</li>
          <li>Zena is NOT a licensed investment adviser, broker, or asset manager.</li>
          <li>Zena does NOT provide financial, investment, legal, or tax advice.</li>
          <li>Zena does NOT hold custody of your private keys; crypto wallet addresses generated by Zena are custodial wallets managed by Zena on your behalf.</li>
          <li>Zena is NOT a remittance company at this time.</li>
          <li>Zena is NOT a lending company at this time.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'article-3',
    navLabel: 'Article 3 — What Information We Collect',
    cardTitle: 'Article 3 — What Information We Collect',
    content: (
      <>
        <p className={p}>
          We only collect information that is necessary to identify you, run your account, execute your transactions, keep the Platform secure, and comply with our legal obligations. We will always tell you what information we need and why when we ask for it.
        </p>
        <h3 className={h3}>3.1 Identity and KYC Data (You Provide)</h3>
        <ul className={ul}>
          <li>Full legal name and date of birth.</li>
          <li>National Identification Number (NIN).</li>
          <li>Bank Verification Number (BVN) where applicable.</li>
          <li>Government-issued identification document (International Passport, Driver&apos;s Licence, Voter&apos;s Card).</li>
          <li>Selfie image and facial biometric data captured during identity verification.</li>
          <li>Email address and chosen password.</li>
          <li>Phone number.</li>
          <li>Residential address.</li>
          <li>Source of funds documentation (for high-value transactions, as required by regulation).</li>
        </ul>
        <h3 className={h3}>3.2 Financial and Transaction Data (Created When You Transact)</h3>
        <ul className={ul}>
          <li>Bank account details: bank name, account number, account name, payout references.</li>
          <li>Crypto wallet addresses (both Zena-generated addresses and external addresses you provide).</li>
          <li>On-chain transaction IDs (txids), amounts, timestamps, and network details.</li>
          <li>Swap, conversion, and withdrawal records including rates applied and fees charged.</li>
          <li>Gift card trade details: card type, denomination, amount, trade status.</li>
          <li>Utility payment records: service type, recipient reference, amount, status.</li>
          <li>eSIM purchase records.</li>
          <li>E-Trade (OTC) transaction records including agent correspondence.</li>
          <li>Referral activity and reward records.</li>
        </ul>
        <h3 className={h3}>3.3 Device and Technical Data (Collected Automatically)</h3>
        <ul className={ul}>
          <li>IP address and approximate geolocation derived from IP.</li>
          <li>Device type, model, operating system, and application version.</li>
          <li>Browser type and Internet Service Provider (ISP).</li>
          <li>Session data: login timestamps, access times, duration, and activity logs.</li>
          <li>Crash reports and error logs.</li>
          <li>Unique device identifiers and user agents.</li>
        </ul>
        <h3 className={h3}>3.4 Communications Data</h3>
        <ul className={ul}>
          <li>Customer support enquiries, chat transcripts, and email correspondence.</li>
          <li>In-app notifications and messages.</li>
          <li>Any information you voluntarily provide when contacting us.</li>
        </ul>
        <p className={`${p} mt-4`}>
          We do not collect sensitive data beyond what is necessary for identity verification and financial crime compliance. Biometric data (selfie/facial image) is used solely for KYC verification and is not used for any other purpose.
        </p>
      </>
    ),
  },
  {
    id: 'article-4',
    navLabel: 'Article 4 — Your Consent',
    cardTitle: 'Article 4 — Your Consent',
    content: (
      <>
        <p className={p}>
          Your consent is a key basis on which we begin processing your personal data. By accessing and using the Platform, registering an account, or clicking &apos;I Agree&apos;, you are consenting to this Privacy Policy and agreeing to its terms.
        </p>
        <p className={`${p} mt-4`}>
          You have the right to provide, withhold, or withdraw your consent to data processing at any time. To withdraw consent, please contact us at privacy@zenaex.com. Please note that withdrawing consent may affect your ability to access or use certain Zena Services.
        </p>
        <p className={`${p} mt-4`}>
          Please refer to Sections 25–27 of the Nigeria Data Protection Act (NDPA) 2023 for a full understanding of consent in data processing.
        </p>
      </>
    ),
  },
  {
    id: 'article-5',
    navLabel: 'Article 5 — Legal Bases for Processing',
    cardTitle: 'Article 5 — Legal Bases for Processing',
    content: (
      <>
        <p className={p}>We process your personal data only where we have a lawful basis to do so under the NDPA. The legal bases we rely on are:</p>
        <ul className={ul}>
          <li>
            <strong className="font-semibold text-primary-black">Contract:</strong> Processing necessary to provide the services you have requested, including account creation, executing transactions, and delivering payouts.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Legal Obligation:</strong> Processing required to comply with applicable laws, including AML/CFT obligations, CBN regulatory requirements, NDPC directives, and court orders.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Legitimate Interests:</strong> Processing necessary for fraud prevention, Platform security, improving user experience, and protecting the integrity of the financial system, where such interests are not overridden by your rights.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Consent:</strong> You have provided explicit consent (e.g. marketing communications). You may withdraw consent at any time without this affecting the lawfulness of prior processing.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'article-6',
    navLabel: 'Article 6 — How We Use Your Information',
    cardTitle: 'Article 6 — How We Use Your Information',
    content: (
      <>
        <p className={p}>We use the personal data we collect for the following specific purposes:</p>
        <ul className={ul}>
          <li>
            <strong className="font-semibold text-primary-black">Account Registration and Access:</strong> To create, manage, and authenticate your Zena Account.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Identity Verification (KYC):</strong> To confirm your identity using NIN-derived fields, government ID, and biometric data as required by law.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Transaction Processing:</strong> To execute crypto send/receive/swap operations, fiat conversions, bank payouts, utility payments, gift card trades, eSIM purchases, and E-Trade transactions.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Fraud Prevention and AML/CFT Compliance:</strong> To detect, investigate, and prevent fraudulent activity, money laundering, terrorist financing, and other financial crimes. This includes sanctions screening and transaction monitoring.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Regulatory Reporting:</strong> To report to the CBN, NFIU, EFCC, NDPC, and other competent authorities as required by applicable law.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Customer Support:</strong> To respond to your enquiries, resolve disputes, process complaints, and provide service updates.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Transactional Notifications:</strong> To send receipts, transaction confirmations, security alerts, and important account notices.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Referral Programme Management:</strong> To track referral activity and attribute and process referral rewards.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Platform Improvement:</strong> To analyse usage patterns, diagnose technical issues, conduct research, and improve the functionality and user experience of the Platform.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Marketing Communications:</strong> To send you promotional content, product updates, and offers where you have opted in. You may opt out at any time.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Legal and Compliance Purposes:</strong> To enforce these Terms of Use, protect our legal rights, and respond to valid legal process.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 'article-7',
    navLabel: 'Article 7 — Cookies and Website Tracking',
    cardTitle: 'Article 7 — Cookies and Website Tracking',
    content: (
      <>
        <p className={p}>
          To enhance your experience and improve our Platform, we use cookies and similar tracking technologies. Cookies are small data files stored on your device when you visit our website or use our application.
        </p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Types of Cookies We Use</p>
        <ul className={ul}>
          <li>
            <strong className="font-semibold text-primary-black">Essential Cookies:</strong> Required for core Platform functionality, including authentication and session management. The Platform cannot function correctly without these.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Analytics Cookies:</strong> Used to understand how Users interact with the Platform, measure traffic, and identify performance issues (e.g., usage patterns, page views).
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Security Cookies:</strong> Used to detect, investigate, and prevent fraudulent and unauthorised activity.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Preference Cookies:</strong> Used to remember your settings and customisations for a better experience.
          </li>
        </ul>
        <p className={`${p} mt-4`}>
          We do not use cookies to collect personal information without your consent, and we do not share cookie data with third parties for advertising purposes.
        </p>
        <p className={`${p} mt-4`}>
          By using our Platform, you consent to our use of cookies in accordance with this Policy. You may manage or disable cookies through your browser settings at any time. Please note that disabling essential cookies may impair your ability to use the Platform.
        </p>
      </>
    ),
  },
  {
    id: 'article-8',
    navLabel: 'Article 8 — Log Files',
    cardTitle: 'Article 8 — Log Files',
    content: (
      <>
        <p className={p}>Zena follows standard industry practice in using log files. These files automatically record activity when Users access the Platform. Log file data may include:</p>
        <ul className={ul}>
          <li>Internet Protocol (IP) addresses.</li>
          <li>Browser type and version.</li>
          <li>Internet Service Provider (ISP).</li>
          <li>Date and time of access.</li>
          <li>Referring and exit pages.</li>
          <li>Number of clicks and navigation paths.</li>
        </ul>
        <p className={`${p} mt-4`}>
          Log file data is not personally identifiable on its own. We use this information to analyse usage trends, manage and maintain the Platform, track User movement patterns, and gather aggregate demographic data. Log data is retained for a limited period and then securely deleted or anonymised.
        </p>
      </>
    ),
  },
  {
    id: 'article-9',
    navLabel: 'Article 9 — How We Share Your Personal Data',
    cardTitle: 'Article 9 — How We Share Your Personal Data',
    content: (
      <>
        <p className={p}>
          We share your personal data only where necessary and only with the following categories of recipients. We do not sell, rent, or trade your personal data to any third party for commercial purposes.
        </p>
        <h3 className={h3}>9.1 Payment and Banking Partners</h3>
        <p className={p}>
          We share necessary data (including account details and transaction records) with banks, payment processors, and mobile money providers to complete payouts and other financial operations you request. Current processor partners include Monnify, Quidex, Paystack, and Blusalt, subject to change.
        </p>
        <h3 className={h3}>9.2 KYC and Identity Verification Providers</h3>
        <p className={p}>
          We share your identity documents, NIN, BVN, and biometric data with authorised third-party KYC/identity verification providers to perform identity checks required by law. These providers act as data processors under binding contractual obligations.
        </p>
        <h3 className={h3}>9.3 Utility and Service Providers</h3>
        <p className={p}>
          For utility payments, gift card trades, and eSIM purchases, we share the minimum data necessary with authorised third-party service providers (such as VTPass, Baxi, and Buypower) to complete your requested transaction.
        </p>
        <h3 className={h3}>9.4 Transaction Counterparties</h3>
        <p className={p}>
          When you use Zena Services to transact with another User or a third-party platform, we may share limited data (such as transaction reference, amount, and account details) necessary to complete and record the transaction and to support dispute resolution or fraud prevention.
        </p>
        <h3 className={h3}>9.5 Cloud Infrastructure and Technology Providers</h3>
        <p className={p}>
          We share data with cloud hosting, data storage, and software infrastructure providers that host and support the Platform. All such providers are bound by data processing agreements and required to maintain appropriate security standards.
        </p>
        <h3 className={h3}>9.6 Credit Reference and Fraud Prevention Agencies</h3>
        <p className={p}>
          Where permitted by law, we may share data with credit reference agencies and fraud prevention databases to carry out anti-fraud checks, sanctions screening, and compliance verifications, in accordance with applicable data protection regulations.
        </p>
        <h3 className={h3}>9.7 Business Transfers</h3>
        <p className={p}>
          In the event of a merger, acquisition, restructuring, or sale of all or part of our business, your personal data may be transferred to the successor entity, subject to equivalent data protection obligations. We will notify you of any such transfer in advance where legally required.
        </p>
        <h3 className={h3}>9.8 With Your Consent</h3>
        <p className={p}>We will share your data with any other party where you have provided explicit, informed consent for us to do so.</p>
        <h3 className={h3}>9.9 Legal and Regulatory Disclosure</h3>
        <p className={p}>
          We may disclose your data to comply with applicable law, respond to valid legal process, or as required by regulatory authorities. See Article 10 for details on law enforcement requests.
        </p>
        <p className={`${p} mt-4`}>
          We ensure all third-party service providers with whom we share personal data have compliant, legally enforceable data protection measures in place before we share any data with them.
        </p>
      </>
    ),
  },
  {
    id: 'article-10',
    navLabel: 'Article 10 — Law Enforcement and Official Requests',
    cardTitle: 'Article 10 — Law Enforcement and Official Requests',
    content: (
      <>
        <p className={p}>
          Competent authorities, law enforcement agencies, and government bodies may submit formal data requests to Zena. All such requests must be sent in writing to:
        </p>
        <p className={`${p} mt-4`}>
          <strong className="font-semibold text-primary-black">Law Enforcement Requests:</strong> lawenforcement@zenaex.com
        </p>
        <p className={`${p} mt-4`}>
          Where a request is lawful, valid, and properly documented, Zena may provide only the information we hold that is responsive to the specific request. This may include:
        </p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Identity Data</p>
        <ul className={ul}>
          <li>Full name, email address, phone number, and NIN.</li>
          <li>Identity documents submitted during KYC.</li>
          <li>Selfie/biometric image (if collected).</li>
          <li>Residential address derived from NIN or provided by the User.</li>
        </ul>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Operational Data</p>
        <ul className={ul}>
          <li>IP addresses and device identifiers at specific timestamps.</li>
          <li>Account creation date, login timestamps, and session data.</li>
        </ul>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Transaction and Service Records</p>
        <ul className={ul}>
          <li>Crypto wallet addresses generated by Zena for the User.</li>
          <li>On-chain transaction IDs (txids), amounts, timestamps, and network details.</li>
          <li>Bank payout details: bank name, account name, account number, payout references.</li>
          <li>Gift card trade records, utility payment records, and eSIM purchase records.</li>
        </ul>
        <p className={`${p} mt-4`}>
          Zena may preserve records upon written request from a competent authority. Where an account freeze or asset restriction is sought, a valid court order or equivalent legal authority from a Nigerian court or regulatory body is required. Zena uses secure channels for all data transfers to competent authorities.
        </p>
      </>
    ),
  },
  {
    id: 'article-11',
    navLabel: 'Article 11 — How We Protect Your Personal Data',
    cardTitle: 'Article 11 — How We Protect Your Personal Data',
    content: (
      <>
        <h3 className={`${h3} mt-0`}>11.1 Technical Measures</h3>
        <ul className={ul}>
          <li>End-to-end encryption for all data in transit using TLS/SSL protocols.</li>
          <li>Encryption of sensitive data at rest, including identity documents and financial records.</li>
          <li>Multi-factor authentication (MFA) required for account access.</li>
          <li>Transaction PIN and optional biometric authentication for in-app operations.</li>
          <li>Firewalls, intrusion detection systems, and real-time threat monitoring.</li>
          <li>Regular penetration testing and security audits.</li>
        </ul>
        <h3 className={h3}>11.2 Organisational Measures</h3>
        <ul className={ul}>
          <li>Role-based access controls ensuring only authorised personnel can access personal data.</li>
          <li>Regular data protection training for all staff handling personal data.</li>
          <li>Documented data handling policies and incident response procedures.</li>
          <li>CCTV and physical access controls at all operational premises.</li>
        </ul>
        <h3 className={h3}>11.3 Your Responsibilities</h3>
        <p className={p}>While Zena maintains robust security measures, your own conduct also contributes to the safety of your account. You are responsible for:</p>
        <ul className={ul}>
          <li>Maintaining a strong, unique password and not sharing it with any third party.</li>
          <li>Keeping your transaction PIN confidential.</li>
          <li>Ensuring your device is secure and up to date.</li>
          <li>Reporting any suspected unauthorised access to your account immediately to support@zenaex.com.</li>
        </ul>
        <h3 className={h3}>11.4 Data Breach Notification</h3>
        <p className={p}>
          In the unlikely event of a personal data breach that is likely to result in a high risk to your rights and freedoms, Zena will notify you and the Nigeria Data Protection Commission (NDPC) within 72 hours of becoming aware of the breach, in accordance with the NDPA 2023.
        </p>
        <h3 className={h3}>11.5 DPO Remedies and Timeline</h3>
        <p className={p}>
          In the event of a violation of your data rights, our Data Protection Officer (DPO) shall, within 30 days of receiving notice of the violation, address the issue and implement appropriate remedies. Available remedies include correction, deletion, restriction of processing, granting access to your data, or such other remedies as the applicable law prescribes.
        </p>
      </>
    ),
  },
  {
    id: 'article-12',
    navLabel: 'Article 12 — Data Retention',
    cardTitle: 'Article 12 — Data Retention',
    content: (
      <>
        <p className={p}>
          We retain your personal data only for as long as is necessary to fulfil the purposes for which it was collected, subject to the following minimum retention periods required by Nigerian law:
        </p>
        <ul className={ul}>
          <li>KYC and identity records (NIN, passport, biometrics): Minimum 5 years after account closure, in compliance with CBN AML/CFT Regulations.</li>
          <li>Transaction records (all financial transactions): Minimum 5 years from the date of the transaction.</li>
          <li>Log files and technical data: 12 months from the date of collection.</li>
          <li>Customer support and communications records: 2 years from resolution of the matter.</li>
          <li>Marketing data and opt-in records: Until you withdraw consent.</li>
        </ul>
        <p className={`${p} mt-4`}>
          After the applicable retention period expires, data is securely deleted, destroyed, or irreversibly anonymised in accordance with our data disposal procedures.
        </p>
      </>
    ),
  },
  {
    id: 'article-13',
    navLabel: 'Article 13 — International Data Transfers',
    cardTitle: 'Article 13 — International Data Transfers',
    content: (
      <>
        <p className={p}>
          Your personal data may be stored or processed outside Nigeria by our cloud infrastructure, identity verification, or service providers. Where we transfer personal data internationally, we ensure that such transfers are protected by appropriate safeguards as required by the NDPA 2023, including:
        </p>
        <ul className={ul}>
          <li>Standard Contractual Clauses (SCCs) approved by the NDPC.</li>
          <li>Adequacy determinations where the destination country is deemed to provide an adequate level of protection.</li>
          <li>Your explicit consent where required.</li>
        </ul>
        <p className={`${p} mt-4`}>
          We only transfer data to jurisdictions or providers that meet appropriate data protection standards, and all transfers are governed by binding contractual obligations.
        </p>
      </>
    ),
  },
  {
    id: 'article-14',
    navLabel: 'Article 14 — Your Data Protection Rights',
    cardTitle: 'Article 14 — Your NDPA Data Protection Rights',
    content: (
      <>
        <p className={p}>Under the Nigeria Data Protection Act (NDPA) 2023, you have the following rights in relation to your personal data:</p>
        <ul className={ul}>
          <li>
            <strong className="font-semibold text-primary-black">Right to Be Informed:</strong> The right to know what personal data we collect about you, why we collect it, and how it is processed.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right of Access:</strong> The right to request a copy of the personal data we hold about you, free of charge, unless public policy or regulation provides otherwise.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Rectification:</strong> The right to request correction of any personal data we hold about you that is inaccurate, incomplete, or outdated.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Erasure (&apos;Right to Be Forgotten&apos;):</strong> The right to request deletion of your personal data where it is no longer necessary for the purpose it was collected, subject to our legal retention obligations.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Object:</strong> The right to object to or withdraw consent for processing based on legitimate interests or for direct marketing at any time.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Restriction:</strong> The right to request that we restrict or limit the processing of your personal data in certain circumstances (e.g., while accuracy is being verified).
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Data Portability:</strong> The right to receive your personal data in a structured, commonly used, machine-readable format and to have it transferred to another provider where technically feasible.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Know Data Controller / Processor Details:</strong> The right to know the identity and contact details of the data controller and any processors acting on our behalf.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Remediation:</strong> The right to seek remedy and redress in the event of a breach of your privacy rights, including through our DPO and through the NDPC.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Lodge a Complaint:</strong> The right to lodge a formal complaint with the Nigeria Data Protection Commission (NDPC) at www.ndpc.gov.ng if you believe your data rights have been violated.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Be Informed of International Transfers:</strong> The right to be informed when your personal data is transferred to another country.
          </li>
          <li>
            <strong className="font-semibold text-primary-black">Right to Be Informed of New Purposes:</strong> The right to be informed if your personal data is processed for any purpose beyond what was stated at the time of collection.
          </li>
        </ul>
        <p className={`${p} mt-4`}>
          To exercise any of the above rights, please contact our Data Protection Officer at: dpo@zenaex.com. We will verify your identity before processing your request and will respond within 30 days of receipt.
        </p>
      </>
    ),
  },
  {
    id: 'article-15',
    navLabel: "Article 15 — Children's Information",
    cardTitle: "Article 15 — Children's Information",
    content: (
      <>
        <p className={p}>
          Zena is not intended for use by individuals under the age of 18. We do not knowingly collect, store, or process personal data from children under 18 years of age. If you are a parent or guardian and believe that your child has submitted personal information through the Platform without your knowledge, please contact us immediately at privacy@zenaex.com.
        </p>
        <p className={`${p} mt-4`}>
          Upon receiving and verifying such a report, we will promptly delete the child&apos;s data from our records. We strongly encourage parents and guardians to monitor and supervise their children&apos;s online activities.
        </p>
      </>
    ),
  },
  {
    id: 'article-16',
    navLabel: 'Article 16 — Changes to This Privacy Policy',
    cardTitle: 'Article 16 — Changes to This Privacy Policy',
    content: (
      <>
        <p className={p}>
          We retain the right to update or modify this Privacy Policy at any time to reflect changes in our practices, applicable law, regulatory requirements, or operational needs. When we make material changes, we will:
        </p>
        <ul className={ul}>
          <li>Post the updated Policy on the Platform and update the &apos;Last Updated&apos; date.</li>
          <li>Notify you via in-app notification or email at least 14 days before the changes take effect.</li>
        </ul>
        <p className={`${p} mt-4`}>
          If you do not agree with any changes to this Policy, you must discontinue use of the Platform before they take effect. Your continued use of the Platform after the effective date of any changes constitutes your acceptance of the updated Policy.
        </p>
        <p className={`${p} mt-4`}>We encourage you to review this Privacy Policy periodically to stay informed about how we are protecting your data.</p>
      </>
    ),
  },
  {
    id: 'article-17',
    navLabel: 'Article 17 — Contact Us',
    cardTitle: 'Article 17 — Contact Us',
    content: (
      <>
        <p className={p}>
          If you have any questions, requests, or complaints about this Privacy Policy or how we handle your personal data, please contact us through the appropriate channel below:
        </p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>General Privacy Enquiries and User Rights Requests</p>
        <p className={p}>Email: privacy@zenaex.com</p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Data Protection Officer (DPO)</p>
        <p className={p}>Email: dpo@zenaex.com</p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Legal and Compliance</p>
        <p className={p}>Email: legal@zenaex.com</p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Law Enforcement Requests Only</p>
        <p className={p}>Email: lawenforcement@zenaex.com</p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Registered Address</p>
        <p className={p}>Zena Technologies Limited</p>
        <p className={p}>Lagos, Nigeria</p>
        <p className={p}>Website: www.zenaex.com</p>
        <p className={`${p} mt-4 font-semibold text-primary-black`}>Regulatory Complaints</p>
        <p className={p}>
          If you are not satisfied with our response to your data rights request or believe your rights have been violated, you may also lodge a formal complaint with:
        </p>
        <p className={`${p} mt-4`}>Nigeria Data Protection Commission (NDPC)</p>
        <p className={p}>Website: www.ndpc.gov.ng</p>
        <p className={`${p} mt-8 border-t border-gray-200 pt-6 text-sm text-gray-500`}>
          © 2026 Zenaex Technologies Limited. All rights reserved. | Privacy Policy — Last Updated: 2026
        </p>
      </>
    ),
  },
];
